version: '3.9'

# ======================================= Services ======================================
services:

  database:
    build: deployement/database
    image: database
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database:${CONTAINER_DATABASE_VLPATH}
    networks:
      - ft_transcendence

  backend:
    build:
      dockerfile: deployement/backend/Dockerfile
      context: .
    image: backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080
    volumes:
      - backend:${CONTAINER_BACKEND_VLPATH}
    networks:
      - ft_transcendence

  frontend:
    build:
      dockerfile: deployement/frontend/Dockerfile
      context: .
    image: frontend
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000
    depends_on:
      - database
      - backend
    volumes:
      - frontend:${CONTAINER_FRONTEND_VLPATH}
    networks:
      - ft_transcendence

  webserver:
    build: deployement/webserver
    image: webserver
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
      - backend
      - frontend
    env_file:
      - .env
    networks:
      - ft_transcendence
# =======================================================================================



# ======================================= Networks ======================================
networks:
  ft_transcendence:
    name: ft_transcendence
# =======================================================================================



# ======================================= Volumes =======================================
volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_FRONTEND_VLPATH}
  backend:
    name: backend
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_BACKEND_VLPATH}
  database:
    name: database
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_DATABASE_VLPATH}
# =======================================================================================
