version: '3.9'

# ======================================= Services ======================================
services:

  database:
    build: deployement/database
    image: database
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    # volumes:
    #   - database:${CONTAINER_DATABASE_VLPATH}
    networks:
      - ft_transcendence
  

  backend:
    build:
      context: .
      dockerfile: deployement/backend/Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080
    networks:
      - ft_transcendence

  frontend:
    build:
      context: .
      dockerfile: deployement/frontend/Dockerfile
    image: frontend
    container_name: frontend
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000
    depends_on:
      - database
      - backend
    networks:
      - ft_transcendence
    volumes:
      - static-content:/var/www/html

  webserver:
    image: caddy/caddy:2.2.1-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
      - backend
      - frontend
    networks:
      - ft_transcendence
    volumes:
        - static-content:/var/www/html
        - ./deployement/webserver/srcs/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config


networks:
  ft_transcendence:
    name: ft_transcendence

volumes:
  caddy_data:
  caddy_config:
  static-content:
