version: '3.9'

services:

  postgres:
    build: requirements/postgres
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - DB:${POSTGRES_DB_PATH}
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    name: ft_transcendence

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_DB_PATH}
