version: '3.9'

# ======================================= Services ======================================
services:

  postgres:
    build: services/database
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:${CONTAINER_DATABASE_VLPATH}
    networks:
      - ft_transcendence

  react:
    build: services/frontend
    image: react
    container_name: react
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - frontend:${CONTAINER_FRONTEND_VLPATH}
    networks:
      - ft_transcendence

  nestjs:
    build: services/backend
    image: nestjs
    container_name: nestjs
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - backend:${CONTAINER_BACKEND_VLPATH}
    networks:
      - ft_transcendence
    
  webserver:
    build: services/webserver
    image: webserver
    container_name: webserver
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - ft_transcendence
# =======================================================================================



# ======================================= Networks ======================================
networks:
  ft_transcendence:
    name: ft_transcendence
# =======================================================================================



# ======================================= Volumes =======================================
volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_FRONTEND_VLPATH}
  backend:
    name: backend
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_BACKEND_VLPATH}
  database:
    name: database
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${LOCAL_DATABASE_VLPATH}
# =======================================================================================
